name: CI/CD for Angular App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.4]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build -- --configuration=production

      - name: Build project
        run: npm run build -- --configuration=production

  deploy:
    runs-on: ubuntu-latest
    needs: build # Ensure the deploy job only runs after the build job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/form-app # Replace with your app's output directory
